name: Run Start File

on:
  push:
    branches:
      - main
  workflow_dispatch: # позволяет запускать вручную из интерфейса GitHub

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run start file
        run: |
          chmod +x start.sh # Убедитесь, что файл имеет права на выполнение
          ./start.sh # Запуск файла start.sh
